"""app/config/localhost.py
"""
DEBUG = True
# SECRET_KEY is generated by os.urandom(24).
SECRET_KEY = '\xf7\xf4\x9bb\xd7\xa8\xdb\xee\x9f\xe3\x98SR\xda\xb0@\xb7\x12\xa4uB\xda\xa3\x1b'
STRIPE_API_KEY = ''
JSON_AS_ASCII = False

SQLALCHEMY_DATABASE_URI = '{sql}+{driver}://{user}:{password}@{host}:{port}/{database}'.format(**{
    'sql': 'postgresql',
    'driver': 'psycopg2',
    'user': 'postgres',
    'password': 'postgres',
    'host': 'localhost',
    'port': '5432',
    'database': 'feedback'
})
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = True
SQLALCHEMY_ENGINE_OPTIONS = {
    'pool_size': 5,
    'max_overflow': 10,
    'pool_timeout': 30
}
